version: '3.4'

services:

  nginx:
    container_name: {{NAME}}-nginx
    image: nginx:latest
    restart: always
    ports:
      - "7000:80"
      - "7001:443"
    volumes:
      - ./public:/var/www/html/public
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/log:/var/log/nginx
    depends_on:
      - php
    links:
      - php
    networks:
      - {{NAME}}-network

  php:
    container_name: {{NAME}}-php
    image: marcelofabianov/php-dbs
    restart: always
    working_dir: /var/www/html
    ports:
      - "7002:9000"
    volumes:
      - .:/var/www/html
    networks: 
      - {{NAME}}-network

  mysql:
    container_name: {{NAME}}-mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "app"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    ports:
      - "7003:3306"
    networks:
      - {{NAME}}-network

networks:
  {{NAME}}-network:
    driver: bridge

